apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: clang-tidy-scan-
spec:
  entrypoint: clang-tidy-workflow
  # Mount Docker config for Kaniko
  volumes:
    - name: docker-config
      secret:
        secretName: docker-config
        items:
          - key: .dockerconfigjson
            path: config.json

  templates:
    - name: clang-tidy-workflow
      dag:
        tasks:
          - name: build-image
            template: kaniko-build
          - name: scan-includes
            template: scan-includes
            dependencies: [build-image]
          - name: scan-cuda-source
            template: scan-cuda-source
            dependencies: [build-image]
          - name: scan-test-files
            template: scan-test-files
            dependencies: [build-image]

    - name: kaniko-build
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - --context=git://github.com/Gin-G/micm-ncote.git
          - --dockerfile=docker/Dockerfile.clang-tidy
          - --destination={{inputs.parameters.DOCKERHUB_USERNAME}}/micm-clang-tidy:{{inputs.parameters.DATE_TAG}}
          - --cache=true
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker/
        env:
          - name: HOME
            value: /root

    - name: scan-includes
      container:
        image: "{{inputs.parameters.DOCKERHUB_USERNAME}}/micm-clang-tidy:{{inputs.parameters.DATE_TAG}}"
        command: [bash, -c]
        args:
          - |
            INCLUDE_FILES=$(find include -type f \( -name '*.hpp' -o -name '*.h' -o -name '*.cuh' -o -name '*.inl' \) | grep -v jit | grep -v '.inl' | grep -v '.cuh' )
            echo "scanning include files:"
            echo ${INCLUDE_FILES} | tr " " "\n"
            time clang-tidy -p ./build/ --config-file="./.clang-tidy" \
              -header-filter=$(pwd)/include/.* \
              --extra-arg "-lcudart_static" \
              --extra-arg "-std=c++20" \
              ${INCLUDE_FILES} -- -Iinclude/ \
              -isystem ./cuda-build/_deps/json-src/include
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"

    - name: scan-cuda-source
      container:
        image: "{{inputs.parameters.DOCKERHUB_USERNAME}}/micm-clang-tidy:{{inputs.parameters.DATE_TAG}}"
        command: [bash, -c]
        args:
          - |
            SOURCE_FILES=$(find src -type f \( -name '*.cu' -o -name '*.hpp' -o -name '*.h' -o -name '*.cpp' \))
            echo "scanning src files:"
            echo ${SOURCE_FILES} | tr " " "\n"
            time clang-tidy -p ./cuda-build/ --config-file="./.clang-tidy" \
              -header-filter=$(pwd)/include/.* \
              --extra-arg "-lcudart_static" \
              --extra-arg "-std=c++20" \
              --extra-arg "--cuda-gpu-arch=sm_70" \
              ${SOURCE_FILES} -- -Iinclude/ \
              -isystem ./cuda-build/_deps/googletest-src/googletest/include \
              -isystem ./cuda-build/_deps/json-src/include
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"

    - name: scan-test-files
      container:
        image: "{{inputs.parameters.DOCKERHUB_USERNAME}}/micm-clang-tidy:{{inputs.parameters.DATE_TAG}}"
        command: [bash, -c]
        args:
          - |
            TEST_FILES=$(find test -type f \( -name '*.hpp' -o -name '*.h' -o -name '*.cpp' -o -name '*.cuh' -o -name '*.cu' \) ! -path 'test/tutorial/*'  ! -path '**/*.cuh' ! -path '**/*jit*' )
            echo "scanning test files:"
            echo ${TEST_FILES} | tr " " "\n"
            time clang-tidy -p ./cuda-build/ --config-file="./.clang-tidy" \
              -header-filter=$(pwd)/include/.* \
              --extra-arg "-lcudart_static" \
              --extra-arg "-std=c++20" \
              --extra-arg "--cuda-gpu-arch=sm_70" \
              ${TEST_FILES} -- -Iinclude/ \
              -isystem ./cuda-build/_deps/googletest-src/googletest/include \
              -isystem ./cuda-build/_deps/json-src/include
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"

  arguments:
    parameters:
      - name: REPO_URL
        value: "https://github.com/your-org/your-repo.git"  # Replace with your repo URL
      - name: REPO_COMMIT
        value: "main"  # Or specific commit/branch
      - name: DOCKERHUB_USERNAME
        value: ""  # Will be passed from GitHub Actions
      - name: DATE_TAG
        value: ""  # Will be passed from GitHub Actions