name: Clang-Format

on:
  pull_request:

jobs:
  format:
    name: Run Clang-Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Clang-Format
        run: sudo apt-get update && sudo apt-get install clang-format

      - name: Run Clang-Format
        run: |
          clang-format -i --style=file include/**/*.hpp
          clang-format -i --style=file src/**/*.cu
          clang-format -i --style=file test/**/*.hpp test/**/*.cpp

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Auto-format code using Clang-Format" || echo "No changes to commit"
