name: Clang-Format

on:
  pull_request:
    paths:
      - '**/*.{cpp,h,c,hpp}'   # Specify the file types you want Clang-Format to run on

jobs:
  format:
    name: Run Clang-Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Clang-Format
        run: sudo apt-get update && sudo apt-get install clang-format

      - name: Run Clang-Format
        run: 
          clang-format -i --style=file include/**/*.hpp include/**/*.h
          clang-format -i --style=file src/**/*.hpp src/**/*.h src/**/*.cpp src/**/*.cu
          clang-format -i --style=file test/**/*.hpp src/**/*.h src/**/*.cpp

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Auto-format code using Clang-Format" || echo "No changes to commit"
