name: Docker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker-build-and-test:
    name: Build and Test - ${{ matrix.dockerfile }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dockerfile:
          - Dockerfile
          - Dockerfile.coverage
          - Dockerfile.llvm
          - Dockerfile.memcheck
          - Dockerfile.no_json
          - Dockerfile.nvhpc
          - Dockerfile.openmp
          - Dockerfile.intel 
          # - Dockerfile.mpi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Build Docker image
        run: podman build -t micm -f docker/${{ matrix.dockerfile }} . --format=docker

      - name: Run tests in container
        # only run this if we are not running coverage tests or have built the cuda files
        if: matrix.dockerfile != 'Dockerfile.coverage'
        run: podman run --name test-container -t micm bash -c 'make test ARGS="--rerun-failed --output-on-failure -j8"'

      - name: Run coverage tests in container
        if: matrix.dockerfile == 'Dockerfile.coverage'
        run: podman run --name test-container -t micm bash -c 'make coverage ARGS="--rerun-failed --output-on-failure -j8"'

      - name: Copy coverage from container
        if: matrix.dockerfile == 'Dockerfile.coverage'
        run: podman cp test-container:build/coverage.info .
