name: Assigns new issues to a project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project board
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v1.0.1    
        with:
          project-url: https://github.com/orgs/NCAR/projects/51
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
