name: build

on: [push, pull_request]

jobs:
  multiple-platform-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        compiler:
          - {cpp: g++, c: gcc}
          - {cpp: clang++, c: clang}
          - {cpp: cl, c: cl}
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake .. \
            -DENABLE_REGRESSION_TESTS=OFF
          make VERBOSE=1

      - name: Run tests
        run: |
          cd build
          make test ARGS="--rerun-failed --output-on-failure -j8"
